In [4]:
import numpy as np

In [5]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [8]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
type(z[0])

numpy.float64

In [11]:
z.shape

(10,)

In [17]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
z = np.ones(5)
z

array([1., 1., 1., 1., 1.])

In [23]:
z = np.empty(3)
z

array([4.63964678e-310, 1.89721208e-321, 2.12199580e-313])

In [24]:
f = np.linspace(2,10,5)
f

array([ 2.,  4.,  6.,  8., 10.])

In [26]:
h = np.array([10,20])
h

array([10, 20])

In [29]:
a_list = [1,2,3,4,5]
z = np.array([a_list])
z

array([[1, 2, 3, 4, 5]])

In [30]:
b_list = [[9,8,7,6,5],[4,3,2,1]]
z = np.array([b_list])
z

array([[list([9, 8, 7, 6, 5]), list([4, 3, 2, 1])]], dtype=object)

In [31]:
z.shape

(1, 2)

In [33]:
np.random.seed(0)
z1 = np.random.randint(10, size=6)
z1

array([5, 0, 3, 3, 7, 9])