In [2]:
import numpy as np

## Creiamo alcune matrici con diversi metodi

In [38]:
matrice_full = np.full((4, 3), 12)
print(matrice_full)

[[12 12 12]
 [12 12 12]
 [12 12 12]
 [12 12 12]]


In [39]:
b = np.array([1, 2, 3, 4])

In [11]:
matrice_uniforme = np.random.uniform(1,10)
print(matrice_uniforme)

7.311468805674509


In [40]:
b

array([1, 2, 3, 4])

In [41]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [42]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
matrice_random = np.random.random(10)
print(matrice_random)

[0.48435445 0.39620182 0.11668406 0.12642153 0.04924755 0.6744455
 0.82821848 0.0797676  0.0944463  0.31145897]


In [72]:
matrice_sequenza1 = np.arange(1,10,2)
print(matrice_sequenza1)

[1 3 5 7 9]


In [74]:
matrice_sequenza2 = np.arange(10)
print(matrice_sequenza2)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
matrice_equa = np.linspace(1, 10, 5)
print(matrice_equa)

[ 1.    3.25  5.5   7.75 10.  ]


# Slicing, dimensioni ed altre info sulla matrice

In [43]:
a[1,1]

5

In [44]:
a.ndim

2

In [45]:
b.ndim

1

In [46]:
a.shape

(4, 3)

In [47]:
b.shape

(4,)

In [48]:
a.size

12

# Le Array

In [49]:
array1 = np.ones((3,2))

In [50]:
array1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
array2 = np.zeros((3,4))
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Trasformo tutti valori della matrice da 0 a 10

In [52]:
array2[:] = 10

In [53]:
array2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [54]:
arrayFull = np.full((3,5), 7)
print(arrayFull)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [55]:
arrayRandom = np.random.random(4)
print(arrayRandom)

[0.11841933 0.86581226 0.26847732 0.89173261]


# Le Sequenze

In [56]:
miaSequenza = np.arange(1, 10, 2)
miaSequenza1 = np.arange(10)
miaSequenza2 = np.linspace(1, 10, 6)
print(miaSequenza)
print(miaSequenza1)
print(miaSequenza2)
print(type(miaSequenza))

[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]
[ 1.   2.8  4.6  6.4  8.2 10. ]
<class 'numpy.ndarray'>


## Cambiare Array RESHIPE - RESIZE

In [57]:
matrice = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [58]:
matrice.shape

(4, 3)

RESIZE the total size of array can change RESIZE is the tool

In [59]:
# restituisce la matrice modificata NON tocca originale le dimensioni totali INVARIATE
matrice.reshape(3,4) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
np.resize(matrice, (2,2)) # restituisce None e modifica in place le dimensioni della matrice

array([[1, 2],
       [3, 4]])

In [61]:
a = np.zeros((3,3), dtype=float)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [62]:
af = np.zeros((3,3), dtype=int)

## Fill per riempire tutta la matrice

In [63]:
a.fill(8) # riassegna tutti i valori della matrice IN PLACE
print(a)

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [64]:
a += 3
a

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [65]:
print("Array A\n", a)

Array A
 [[11. 11. 11.]
 [11. 11. 11.]
 [11. 11. 11.]]


`a /= 3`  otterremmo un errore perchè int non può gestire i numeri con virgola. Dobbiamo 
modificare il type degli elementi nella nostra matrice a float

In [66]:
a /=3
a

array([[3.66666667, 3.66666667, 3.66666667],
       [3.66666667, 3.66666667, 3.66666667],
       [3.66666667, 3.66666667, 3.66666667]])

In [67]:
af /=3
af

UFuncTypeError: Cannot cast ufunc 'true_divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

> Perchè in puthon un tipico errore di C? Perchè la libreria numpy è scritta in C...

## Modalità funzionalmente inutile per dichiarare il tipo di variabili

In [ ]:
uno: int
due: str
tre: float

In [ ]:
def miafunzione(x: str) -> str:
    return f'''ciao io sono {x}'''

In [ ]:
miafunzione("andrea")

'ciao io sono andrea'

# arithmetic methods

In [ ]:
a = np.arange(1,10,1, dtype=int)
a.resize(3,3)

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a.sum()

45

In [ ]:
a.sum(0) # somma delle colonne a.sum(axis=0)

array([12, 15, 18])

In [ ]:
a.sum(1) # somma delle righe a.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
a.prod() # 2 * 2 * 2 ... 9 volte

362880

In [ ]:
print('valore massimo:', a.max(),'valore minimo:', a.min())

valore massimo: 9 valore minimo: 1


In [ ]:
a.argmax() # si parte da ZERO 8 indica il nono valore

8

## Peak to peak
> Rappresenta a.max() - a.min()

In [ ]:
peak_to_peak = a.ptp() 
peak_to_peak

8

## Flatten arrays

In [ ]:
a.size

9

In [ ]:
a.reshape(a.size) # una sola riga con 9 colonne

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.flatten() # crea una copia della matrice originale


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.ravel() # crea una visualizzazione della matrice originale (no oggetto)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Repeat values / arrays

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array repeat

In [ ]:
array_repeat = np.repeat(255, 3) 
# alternativa a one e zero
# al posto di 255 mettiamo una array ed otterremo array di 3 array!
print(array_repeat)

[255 255 255]


In [ ]:
repeat_row = np.repeat(a, 3, axis=1)
print(repeat_row)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]


## Array unique

In [ ]:
unique_row = np.unique(repeat_row, axis = 1)
print(unique_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array Diagonal

In [ ]:
np.diagonal(a, offset=0)

array([1, 5, 9])

In [ ]:
np.diagonal(a, offset=1)

array([2, 6])

In [ ]:
np.diagonal(a, offset=-1)

array([4, 8])

## Conversion ad storage

In [ ]:
my_list = a.tolist()
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


> `a.tofile("miofile.txt", sep=",")`
salviamo la matrice su di un file txt usando come separatore la virgola

## Transposition

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Swapaxes

In [ ]:
mat_swap = np.swapaxes(a, 0, 1) 
# colonne per righe, 0 to 1 
# a.swapaxes(0,1)
print(mat_swap)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Transpose

In [ ]:
mat_swap.transpose()



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat_swap.T # capital T significa transpose

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Operations on 2 matrices

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b = a.T
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
simple_ops = a + b
print(simple_ops)

[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


### Floor DIVISION

In [ ]:
floor_division = b // a
# prima esegue la divisione
# arrotonda all'unità inferiore non potendo usare i float
print(floor_division)

[[1 2 2]
 [0 1 1]
 [0 0 1]]
